### ISSUE TITLE
Espaço na inscrição: Erro ao enviar formulário

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/mapasculturais#3]
Quando a relação com espaço é "opcional"

Faça uma relação que precise de validação

Envie o fomulário

O formulário é enviado com sucesso, pq a relação com espaço não é obrigatoria.

No entanto, ele exibe a relação com o Espaço, mas sem trazer os detalhes do espaço.

Nesses casos, a relação deve ser excluída

![captura de tela de 2017-05-22 14-40-18](https://cloud.githubusercontent.com/assets/971483/26321294/988b49aa-3efc-11e7-8d9f-c71edae8fda7.png)

**Comment by arimourao** [comment]
Com o fix da issue #1 o usuário não conseguirá mais enviar a inscrição sem ter a autorização do owner do espaço.
