### ISSUE TITLE
obrigatóriedades questionário museusbr

### ISSUE THREAD

**Issue by arimourao** [medialab-ufg/mapasculturais#8]
museus #71

**Comment by leogermani** [comment]
- [x] Acessibilidade física não tá validando mesmo quando preenche
- [x] Acess física, acess pessoas com def e atendimento a turistas não podem ser obrigatorios (ou tem q ter opção "não tem")
- [x] "complemento" (nos dois endereços) não podem ser obrigatorios

- [x] quando tento salvar com tudo preenchido, dá um erro na primeira aba e aparece um campo de texto flutuando q não dá pra saber o q é
